//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestCook.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int ID { get; set; }
        public string Addres { get; set; }
    }
}
